Add ability to diff/patch states. Closes #36
deepforge-dev/webgme-json-importer pull request #37
Opened 2022-09-09 21:32 UTC by umesh-timalsina

- [ ] Finalize and Test Diffs
        - Currently, nodes are compared according to their Ids. One of the things that makes a criss-cross comparison a bit difficult is because, we might not have access to the `core` api to find/search nodes while just diffing JSONs in one pass (Quicker and Synchronous). And applying only necessary changes in the next pass (Slower and Asynchronous) but only to the parts of the subtree with actual changes. 
- [ ]  Strategy to patch? 
- [ ] Performance Benchmarks?

2022-09-15 18:01 UTC, brollb requested changes
I see a couple selector tests failing. Could you check them out?

2022-09-15 18:29 UTC, brollb commented on src/common/JSONImporter.js
> +                await this.createStateSubTree(this.core.getPath(created), child, resolvedSelectors);
It looks like this is a problem in main, too, so probably not a deal breaker...

2022-09-15 19:16 UTC, umesh-timalsina commented on src/common/JSONImporter.js
> +        async getDiffs(node, state, resolvedSelectors=new NodeSelections()) {
Since we have `changesets.js` already named `diff`. I am not sure, do we want to rename it to not create any confusion?

2022-09-15 19:21 UTC, umesh-timalsina commented on src/common/JSONImporter.js
> +            await this.resolveSelectors(node, currentState, resolvedSelectors);
However, the issue here seems to be that once you have these resolvedSelectors and diffs, the argument node is kind of moot. This means that where in the subtree your patch will be applied, is already determined during diffing.

2022-09-16 14:00 UTC, brollb requested changes

2022-09-16 14:00 UTC, brollb commented on src/common/JSONImporter.js
> +        async patchSync(diffs, resolvedSelectors) {
Maybe leave it async (named `_patch` or something and save the synchronous version for another PR.

2022-09-19 20:40 UTC, brollb approved these changes
I think this should be good to merge. One minor thing is that it might be nice to try to more closely match the format of the patches for `add_subtree` and `delete_subtree`. For example:
```javascript
{
  "type": "put",
  "key": ["children"],
  "value": childState
}
// and
{
  "type": "del",
  "key":  ["children"],
  "value": childPath
}
```

2022-09-20 16:19 UTC, brollb commented
Looks great! Thanks, @umesh-timalsina!

2022-09-20 16:20 UTC, merged